### ISSUE TITLE
Deploying on a node and no i-net connection.

### ISSUE THREAD

**Issue by BobVanB** [echocat/puppet-grafana#12]
We have a internal repo. And i would like to have an option to override the url or change the location of the package like this: 

exec {
    'Download Grafana':
      command => "curl -s -L ${::grafana::package_base}/grafana-${::grafana::version}.tar.gz | tar xz",

**Comment by dwerder** [comment]
The solution you provided is half of an pull request ;-)
So send me one and I will merge it.
