### ISSUE TITLE
Install method

### ISSUE THREAD

**Issue by dhoppe** [echocat/puppet-grafana#15]
Please add support for additional install methods, since Grafana is also available as apt / yum repository.

https://packagecloud.io/grafana/stable/mirror

**Comment by dwerder** [comment]
Thanks for the hint, but this module only supports grafana 1.x . There are more up to date modules for grafana on the forge. The packages provides by grafana are only for grafana 2.x

**Comment by dhoppe** [comment]
Thanks for the info, but the mirror also provides packages for Grafana 3.x.

https://packagecloud.io/grafana/testing/mirror

**Comment by dwerder** [comment]
Take a look at this module. It provides what you need and is approved by puppetlabs:

https://forge.puppet.com/bfraser/grafana

**Comment by dwerder** [comment]
I will update the README to better use that module instead of this one.
