### ISSUE TITLE
Can't install grafana together with dwerder/graphite

### ISSUE THREAD

**Issue by confiq** [echocat/puppet-grafana#8]
Problem is apache class. 
ex

```puppet
class { 'graphite':}
class { 'apache': default_vhost => false }
apache::vhost { 'grafana.sensu.X.com':
    servername      => 'grafana.sensu.X.com',
}
class { 'grafana':}
```
throws:
> Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Package[apache2] is already declared in file /etc/puppet/modules/modules-puppetlabs/apache/manifests/init.pp:99; cannot redeclare at [/etc/puppet/modules/modules-puppetlabs/graphite/manifests/config_apache.pp:20](https://github.com/echocat/puppet-graphite/blob/master/manifests/config_apache.pp#L20) on node sensu.X.com

If I'm having this configuration
```puppet
class { 'graphite':}
apache::vhost { 'grafana.sensu.X.com':
    servername      => 'grafana.sensu.X.com',
}
class { 'grafana':}
```
I'm getting

> Error: Could not retrieve catalog from remote server: Error 400 on SERVER: You must include the apache base class before using any apache defined resources at /etc/puppet/modules/modules-puppetlabs/apache/manifests/vhost.pp:112 on node sensu.X.com

I'm assuming that this module should work together with `dwerder/graphite` but at a moment I'm not sure how.

P.S. Puppet agent/master version 3.7.4

**Comment by dwerder** [comment]
Hi @confiq ,

thats a little bit tricky at the moment. Because the graphite module has a built-in apache install routin. You have to disable it and use the puppetlabs/apache module.

Example:

```
  include '::apache'

  apache::vhost { graphite.my.domain:
    port    => '80',
    docroot => '/opt/graphite/webapp',
    wsgi_application_group      => '%{GLOBAL}',
    wsgi_daemon_process         => 'graphite',
    wsgi_daemon_process_options => {
      processes          => '5',
      threads            => '5',
      display-name       => '%{GROUP}',
      inactivity-timeout => '120',
    },
    wsgi_import_script          => '/opt/graphite/conf/graphite.wsgi',
    wsgi_import_script_options  => {
      process-group     => 'graphite',
      application-group => '%{GLOBAL}'
    },
    wsgi_process_group          => 'graphite',
    wsgi_script_aliases         => {
      '/' => '/opt/graphite/conf/graphite.wsgi'
    },
    headers => [
        'set Access-Control-Allow-Origin "*"',
        'set Access-Control-Allow-Methods "GET, OPTIONS, POST"',
        'set Access-Control-Allow-Headers "origin, authorization, accept"',
     ],
    directories => [{
      path => '/media/',
      order => 'deny,allow',
      allow => 'from all'}
    ]
  }->
 class { 'graphite':
   gr_web_server => 'none'
 }

  apache::vhost { 'grafana.my.domain':
    servername      => 'grafana.my.domain',
    port            => 80,
    docroot         => '/opt/grafana',
    error_log_file  => 'grafana_error.log',
    access_log_file => 'grafana_access.log',
    directories     => [
      {
        path            => '/opt/grafana',
        options         => [ 'None' ],
        allow           => 'from All',
        allow_override  => [ 'None' ],
        order           => 'Allow,Deny',
      }
    ]
  }->
  class {'grafana':
    graphite_host      => 'graphite.my.domain',
    elasticsearch_host => 'elasticsearach.my.domain',
    elasticsearch_port => 9200,
  }
```

I hope that fixes you problem.

**Comment by confiq** [comment]
Yes, after little research i've understand that I should use `class { 'graphite': gr_web_server => 'none'}` and have my own vhost. 

Thanks @dwerder it helped!

**Comment by dwerder** [comment]
The next major version 6 will use the puppetlabs/apache module if you use `gr_web_server => 'apache'` and the default will become 'none'. So that you can provide your own webserver config.

Regards

**Comment by confiq** [comment]
That sounds ideal. 
I don't know how common people get stucked with this problem but if they do, consider to write this in docs.
Thanks again @dwerder :)
